### ISSUE TITLE
Write key must not null or empty

### ISSUE THREAD

**Issue by mash6699** [GetMati/mati-reactnative-plugin#10]
<img width="405" alt="Screen Shot 2021-03-31 at 8 45 52" src="https://user-images.githubusercontent.com/11529233/113163549-82ac1080-91fd-11eb-9dfa-a397c90dea89.png">

Solve this problem please, my decencies are:

"dependencies": {
    "@segment/analytics-react-native": "^1.4.3",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-mati-global-id-sdk": "git+https://github.com/MatiFace/react-native-mati-global-id-sdk.git"
  },

I implemented mati and analytics configuration.

<img width="748" alt="Screen Shot 2021-03-31 at 8 48 37" src="https://user-images.githubusercontent.com/11529233/113164261-2f868d80-91fe-11eb-9048-8f8e025f4aa1.png">

**Comment by aposnovmati** [comment]
Hello @mash6699 we will investigate this conflict and get back to you early next week

**Comment by aposnovmati** [comment]
Hello @mash6699  

we just finished our test and we didnt find any “conflicts” with segment/analytics-react-native”

But we did find out that this library does not work correctly with react native. More precisely, it does not work at all. 

This library doesnt work even if Mati was deleted from project. 

So, please try to reach them directly https://segment.com/docs/ and ask them to fix this issue.

Additional info:
https://segment.com/docs/connections/find-writekey/
https://github.com/segmentio/analytics-react-native/issues/291
https://github.com/segmentio/analytics-react-native/issues/274
https://github.com/segmentio/analytics-react-native/issues/290

But a tip from my side, it is better to integrate with Google analytics, mixpanel, amplitude – directly, for simplicity, you could write your own class of examples on github a lot, it is not necessary to try this library.

**Comment by grifotv** [comment]
I upgraded to `@segment/analytics-react-native` to `1.4.4` as [described here](https://github.com/segmentio/analytics-react-native/issues/291#issuecomment-828659930) and everything works as expected.

**Comment by aposnovmati** [comment]
cool, thanks a lot
