### ISSUE TITLE
MatiSDK does not contain bitcode

### ISSUE THREAD

**Issue by GeDiez** [GetMati/mati-reactnative-plugin#12]
im running into this issue after install MatiSDK package and build my app with XCODE for IOS platform.

```

Showing Recent Messages
'$HOME/my-project/ios/Pods/Mati-Global-ID-SDK/MatiSDK.framework/MatiSDK' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/$HOME/my-project/ios/Pods/Mati-Global-ID-SDK/MatiSDK.framework/MatiSDK' for architecture arm64

```

i dont want disable bitecode for my entire project but i dont know how to disable for this specific target as the warning above says.

- XCode version: 12.4
- MAC OS Big sur 11.2.3
- react-native 0.63.3

STEPS to reproduce:
- install the package
- run pod install in ios folder
- build the project with xcode.
- throws the error described above.

what i did wrong

**Comment by aposnovmati** [comment]
@GeDiez  Hello! Bitcode feature need for support any new architecture, if you will update your app every year or month it will be actual always. Bitcode need only if you publish app and never update it again. If you compile your app this year it will be supported all devices (incl. arm64 of new Apple silicon Macs). Atm we doest support bitcode.

**Comment by aposnovmati** [comment]
@GeDiez Hello, Bitcode was supported in last version, please update)
