### ISSUE TITLE
showFlow() doesn't work in release version

### ISSUE THREAD

**Issue by Kasendwa** [GetMati/mati-reactnative-plugin#14]
Hi. I am having an issue. With the debug version everything is working smoothly. However, when I build a release version of the same, triggering the MatiGlobalIdSdk.showFlow() does absolutely nothing.

This is on Android. I am also using the most recent version of Mati. Have you seen this before? Any help that can be rendered to me?

**Comment by aposnovmati** [comment]
Hello @Kasendwa do you have some errors? what actually version of android sdk, could you provide numbers?)

**Comment by Kasendwa** [comment]
Hi @aposnovmati I don't get an error. It just doesn't do anything. Also, I have no idea which SDK is used. The readme file doesn't specify how to control the SDK to be used. I just followed the readme file.

**Comment by cetric32** [comment]
I have tested on Android 10, in this case, I get stuck. 
Mati is not initiated somehow


In our case, I get stuck there in the screenshot
![Screenshot_20210528-112700](https://user-images.githubusercontent.com/39953557/119956640-f83c1f00-bfa9-11eb-9deb-9201005e127b.png)


Normally, this where We go to the Mati process

**Comment by aposnovmati** [comment]
Ok let me check, i return to you later, probably you have to update android sdk version in gradle file to latest

**Comment by cetric32** [comment]
I have changed to SDK version 30 but the issue still the same. Works in debug version but not in release

**Comment by aposnovmati** [comment]
Hello, we have updated our plugin, please try it

**Comment by cetric32** [comment]
okay, will try it and give feedback

**Comment by Kasendwa** [comment]
Hi @aposnovmati is there an event that we can listen to to notify us if the Mati SDK has initialized? Even in debug mode, sometimes the showFlow works and other times it doesn't. I assume this is because of SDK initialization.

Is there any other team that's using this updated plugin? May be we could learn from them. We haven't rolled out a new app in such a long time because we need to get past this line.

**Comment by Kasendwa** [comment]
Hi @aposnovmati, now the app is crashing at this (both in release and debug versions) for Android.

<img width="751" alt="Screenshot 2021-06-09 at 11 28 07" src="https://user-images.githubusercontent.com/3114425/121320634-011be180-c916-11eb-88d6-873890b8ccff.png">

**Comment by aposnovmati** [comment]
@Kasendwa Hello, looks like plugin (and version of native android sdk inside didn't update)

**Comment by Kasendwa** [comment]
@aposnovmati I have done so, even cleared npm cache and still get the same result. It crashes.

**Comment by aposnovmati** [comment]
@Kasendwa i see by this error you have old package of mati-sdk, do you have android studio?

**Comment by Kasendwa** [comment]
@aposnovmati yes I do have android studio.

**Comment by Kasendwa** [comment]
@aposnovmati I finally have Android working (at least in debug mode). Let me try release mode and revert.

**Comment by aposnovmati** [comment]
@Kasendwa okay, will wait your feedback, thank you

**Comment by Kasendwa** [comment]
@aposnovmati the release version is crashing. See crash report below.

<img width="764" alt="Screenshot 2021-06-09 at 13 40 52" src="https://user-images.githubusercontent.com/3114425/121340560-709acc80-c928-11eb-8366-c6217606ac3e.png">

**Comment by aposnovmati** [comment]
@Kasendwa hello, thank you, let me check it

**Comment by Kasendwa** [comment]
@aposnovmati we really need help rectifying this. We haven't released an update to our app in weeks and we have important issues we need to resolve but are being held back by this Mati issue.

Kindly see the crash on Android release mode. I believe Mati fails to initialize well. However, it works well on debug version.

https://user-images.githubusercontent.com/3114425/122510872-06141b80-d00f-11eb-9998-c4ab339ac3c8.mp4

**Comment by aposnovmati** [comment]
Hello @Kasendwa we cant reproduce this issue, could share yours flow config? maybe via email andrey.posnov@mati.io or we can add you to our slack for fast communication

**Comment by aposnovmati** [comment]
Hello @Kasendwa i will wait for you email or reach out our solution engineers to add you into our slack channel for fast communication
