### ISSUE TITLE
Mati documentation for react implementation isn't accessible

### ISSUE THREAD

**Issue by afroguy16** [GetMati/mati-reactnative-plugin#16]
Is there a documentation for react implementation?

**Comment by aposnovmati** [comment]
@afroguy16 Hello, do you need aolution for mobile application or for web application?

**Comment by afroguy16** [comment]
React web application

**Comment by aposnovmati** [comment]
@afroguy16 try to find it here https://docs.getmati.com/#web-sdk-overview just a few lines of code

**Comment by afroguy16** [comment]
I've read the entire doc and watched the videos, there's no react support. Just a script to paste for a regular html website.

**Comment by aposnovmati** [comment]
@afroguy16  have you tried using this? the code should work with react. Do you have html code in your react project?

**Comment by aposnovmati** [comment]
@afroguy16 ` // Web SDK 
 <script src="https://web-button.mati.io/button.js"></script> 
 <mati-button 
  clientId="clientId" // from your Mati dashboard 
  flowId="flowId" // from your Mati dashboard 
  metadata='{"user_id":"1234778"}' 
 /> `

**Comment by afroguy16** [comment]
No it doesn't, I can't paste a script like that in a react project, that's not how the design work. Don't you have any react support?

**Comment by aposnovmati** [comment]
@afroguy16 we prepared example for you, please check it  
Create React App Example - https://codesandbox.io/s/create-react-app-mati-button-example-77ofi
NextJS Example - https://codesandbox.io/s/next-js-mati-button-example-duypo

**Comment by afroguy16** [comment]
Dope, could you please add this to the code sample for those using TypeScript? The `any` keyword could use some adjustment. I am also updating the title of this issue and closing it so it is easy for others trying to implement this in react to find in Google.

```declare global {
  namespace JSX {
      interface IntrinsicElements {
          'mati-button': any
      }
  }
}
```

**Comment by afroguy16** [comment]
Also is there a way to make the button less opinionated like overriding the style (e.g, the colour switch), removing the Mati logo, etc from the code? Honestly, I would have preferred to hook the call to our own button, is this possible while using your SDK? Or we are stuck with the button style?

**Comment by aposnovmati** [comment]
@afroguy16 1) you can request this feature from our managers 2 and 3) please ask our solution engineers 

Here we doing mobile apps) i think i cant help you with it, sorry. And i will pass info about react examples to our web sdk to update docs
