### ISSUE TITLE
No funiona

### ISSUE THREAD

**Issue by elacquaniti** [GetMati/mati-reactnative-plugin#17]
No esta  funcionando el siguiente plugin
https://github.com/GetMati/mati-reactnative-plugin en IOs cuando en android funciona sin problemas. 
El mismo funcionando sin problemas hasta hace unos días utilizando react native.
https://user-images.githubusercontent.com/5066403/125627655-c61f5d15-12b3-4984-8ec3-a495f79ee4fe.mov
Adjunto un video para mostrar el problema

¿Podrían decirnos si hubo algún cambio en este que debamos aplicar en nuestra aplicación?

**Comment by aposnovmati** [comment]
@elacquaniti Hello, please just reinstall pods in ios folder, by pod update command, we updated our iOS SDK version to 3.2.3 with fix this issue

**Comment by elacquaniti** [comment]
Thanks. IT's works.

**Comment by aposnovmati** [comment]
@elacquaniti good, if you will have new questions/issues please open new ticket
