### ISSUE TITLE
Integración MATI - WEB

### ISSUE THREAD

**Issue by elacquaniti** [GetMati/mati-reactnative-plugin#18]
Estamos integrando MATI con nuestra web y necesitaría saber cuando se termina de subir las imágenes con el botón de <mati-button>(https://docs.getmati.com/#web-sdk-overview). 
Es decir, cuando el mismo finaliza.

No encontramos en la documentación si hay algún evento o variable que indique esto para poder tomar control del flujo luego de esto.

Saludos.= y muchas gracias.

**Comment by aposnovmati** [comment]
Hello @elacquaniti, for example, you can use webhooks for it https://docs.getmati.com/#configure-your-webhook-url
 
This is the repo for Mobile SDK using react-native, if you have any questions about Web-SDK please write to support@getmati.com, and we will provide you all information you need.
